### ISSUE TITLE
[1.12-4.3.0.16] Crash / Workbench Recipe Book

### ISSUE THREAD

**Issue by thatsafy** [progwml6/Natura#392] opened 2017-08-24 12:29 UTC
Client crashes when opening the recipe book while having a workbench open from Natura.  
  
`java.lang.ClassCastException: com.progwml6.natura.common.gui.common.WorkbenchContainer cannot be cast to net.minecraft.inventory.ContainerWorkbench
	at com.progwml6.natura.common.gui.client.WorkbenchGui.func_146284_a(WorkbenchGui.java:158)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at com.progwml6.natura.common.gui.client.WorkbenchGui.func_73864_a(WorkbenchGui.java:138)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by alexbegt** [comment] 2017-08-29 03:01
This is a duplicate of #393, but I have fixed the bug and an update should be posted soon.

**Comment by alexbegt** [comment] 2017-08-29 18:10
This has been fixed with commit [2aa6bd7](https://github.com/progwml6/Natura/commit/2aa6bd7d021ac7079308be2b3de7211c51838d92)

**Closed as completed by alexbegt** 2017-08-29 18:10 UTC
Labels: Bug, 1.12
