### ISSUE TITLE
[1.12-4.3.0.16] Crash when opening the eucalyptus crafting table UI

### ISSUE THREAD

**Issue by megalous** [progwml6/Natura#393] opened 2017-08-26 15:33 UTC
I have just placed a crafting table and tried to open the UI with right-mouse button.
[FML Log](https://pastebin.com/rZFv8Wp5)
[Latest LOG](https://pastebin.com/x7sWJKQV)
[Minecraft Crashreport](https://pastebin.com/KZL0peTs)

Thanks you for still maintaining and working on this mod.

**Comment by Discomanco** [comment] 2017-08-26 16:47
Happens with the Amarantha crafting table as well

**Comment by alexbegt** [comment] 2017-08-29 03:01
This is a duplicate of #392, but I have fixed the bug and an update should be posted soon.

**Comment by alexbegt** [comment] 2017-08-29 18:11
This has been fixed with commit [2aa6bd7](https://github.com/progwml6/Natura/commit/2aa6bd7d021ac7079308be2b3de7211c51838d92)

**Closed as completed by alexbegt** 2017-08-29 18:11 UTC
Labels: Bug, 1.12
