### ISSUE TITLE
[feature request] dynamic trees compat for natura

### ISSUE THREAD

**Issue by malice936** [progwml6/Natura#450] opened 2018-05-21 00:39 UTC
Compatibility for the Natura trees to have dynamic versions, and generate them when [Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees) is installed

**Comment by Zarepheth** [comment] 2018-07-28 01:38
This is a duplicate of [Issue 441](https://github.com/progwml6/Natura/issues/441)

**Comment by alexbegt** [comment] 2018-07-28 03:28
As posted by @Zarepheth This is a duplicate of #441

**Closed as completed** 2018-07-28 03:27 UTC
