### ISSUE TITLE
Unable to get trees to grow

### ISSUE THREAD

**Issue by Gunner76th** [progwml6/Natura#347] opened 2017-04-21 04:43 UTC
While looking through the closed issues I found this one that addressed the situation I am having: https://github.com/progwml6/Natura/issues/325

However, even when I set Sea Level=47 (when standing on dirt block y=57 in journey map), changing the biome to ForestHills, restarting the server, and applying bonemeal in creative for over 5 minutes, I am unable to get the following trees to grow: SilverBell, Willow, Hopseed, Maple. I have tried in both 1 sapling, as well as 2x2 and neither results in tree growth. 

![2017-04-21_00 37 31](https://cloud.githubusercontent.com/assets/5566872/25263046/c5855e18-262a-11e7-9a6c-7d66478688ea.png)
Natura Config https://pastebin.com/CdxTCNre
Natura Modules config https://pastebin.com/P7XmDpBN

Version of Natura in use: 1.10.2-4.1.0.34
Version of Minecraft: 1.10.2
Version of Forge: 2881

Also, the modpack in use is Skyblock, with thermal Expansion added in. All mods had been updated to latest releases available on Curse as of 10 days ago.

**Comment by alexbegt** [comment] 2017-04-21 18:10
In the config file you linked, it seems sea level is set at 64 and not 47, does natura override the value you set whenever you load the mod?

**Comment by Gunner76th** [comment] 2017-04-21 18:17
when I hey home from work I will resubmit our config and double check the
setting.

**Comment by alexbegt** [comment] 2017-04-21 18:20
Okay, Also What client is this pack on? The skyblocks i find on curse are all for 1.7.10 and then wee got modern skyblock for 1.11.2

**Comment by Gunner76th** [comment] 2017-04-21 18:26
the original pack we are based on it FTB SkyFactory 3. the only change is
we added thermal expansion, and changed the mod for Graves. aside from
that, mods are the same, just updated more frequently

**Comment by Gunner76th** [comment] 2017-04-21 18:27
if you look on technic for TEAMIHOC presents SkyWorld that is our pack.
The author is TEAMIhoc challenge

**Comment by Gunner76th** [comment] 2017-04-22 00:07
I have confirmed that sea level is set to 47 on the server (juiceSSH and vi
ftw).

One question I do have is would the fact my client has area level at 64
still matter as long as the server is set to 47?

**Comment by alexbegt** [comment] 2017-04-22 00:41
I just noticed something about the config file in your pack, it has "Sea Level" in two places, which one are you editing? Make sure you are editing the one on line 117, and sorry about "server started" before on your discord, me testing with a server and you send the discord bot info with the client :P

**Comment by alexbegt** [comment] 2017-04-22 00:43
Also If I was you, I wold see about regenerating the config file when you update to natura version of 4.1.0.48 and just disabling everything that you disabled

**Comment by Gunner76th** [comment] 2017-04-22 00:47
I changed the first instance of sea level. and that is interesting.I'll
have to fix that in the client pack tonight

**Comment by alexbegt** [comment] 2017-04-22 01:03
https://pastebin.com/8qCnzQMJ Here is a config file that works for 4.1.0.53/4.1.0.48 it removes the duplicate of "Sea Level" and the "mob changes", and adds the new blacklist for the world gen in dimensions

**Comment by alexbegt** [comment] 2017-04-22 04:19
Bug fixed, It was due to the config <3

**Closed as completed by alexbegt** 2017-04-22 04:19 UTC
